FROM node:22.12-alpine AS build

WORKDIR /app

# Copy package files and install locked dependencies
COPY package*.json .
RUN npm ci

# Copy application code
COPY . .

# Build the application
RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port
EXPOSE 5173
